docker-build-and-push:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - cd app
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.mitchelltsutsulis.com
    - docker build -t registry.mitchelltsutsulis.com/mitchellwt/personal_site .
    - docker push registry.mitchelltsutsulis.com/mitchellwt/personal_site

deploy:
  needs: [docker-build-and-push]
  image: docker:latest
  stage: deploy
  services:
    - name: alpine/git:latest
      alias: git
  script:
    - git clone https://gitlab.mitchelltsutsulis.com/MitchellWT/personal_site_deployment.git
    - docker compose down
    - docker compose up -d
