version: '3.1'

services:
    app:
        container_name: personal_site
        build: app/.
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - personal-site
        ports:
            - 8000:8000
        env_file:
            - ./app.env
    db:
        container_name: personal_site_db
        image: postgres
        restart: unless-stopped
        networks:
            - personal-site
        volumes:
            - ./db:/var/lib/postgresql/data
        env_file:
            - ./db.env
networks:
    personal-site:
