# Generated by Django 4.0.3 on 2022-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=169)),
                ('display_name', models.CharField(max_length=69)),
                ('social_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_image', models.ImageField(upload_to='picture_image')),
                ('title', models.CharField(max_length=69)),
                ('slug', models.CharField(max_length=69)),
                ('location', models.CharField(max_length=169)),
                ('taken_date', models.DateField()),
                ('subjects', models.ManyToManyField(to='portfolio.subject')),
            ],
        ),
    ]
