# Generated by Django 4.0.2 on 2022-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=69),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=69),
        ),
    ]
