# Generated by Django 4.0.2 on 2022-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_slug_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=69),
        ),
    ]
