# Generated by Django 4.0.3 on 2022-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_subject_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Person'), (2, 'Landscape'), (3, 'Architecture')], default=0),
        ),
    ]
