# Generated by Django 4.0.3 on 2022-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_subject_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='portfolio.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='display_name',
            field=models.CharField(blank=True, max_length=69),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=169),
        ),
        migrations.AlterField(
            model_name='subject',
            name='social_link',
            field=models.URLField(blank=True),
        ),
    ]
